#!/bin/python3
import subprocess

metadata = subprocess.check_output(
'''
    playerctl metadata | awk '{$1="" ; print $0 }'
'''
    ,shell=True,text=True)

#print(metadata)

keys=[]
values = []
metadata = metadata.split('\n')
for i in range(len(metadata)) : 
    keys.append(subprocess.check_output(
    '''
    awk '{print $1}'
    '''
        ,shell=True,input=metadata[i],text=True).rstrip()
                )
    
    values.append( subprocess.check_output(
    '''
    awk '{$1="" ;print $0}'
    '''
        ,shell=True,input=metadata[i],text=True).lstrip().rstrip()
                )

data = {}
for i in range(len(metadata)):
    data[keys[i]] = values[i]

subprocess.run(['window_id.py',data['xesam:title']])
